import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation & Layout
    management: 'Management',
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    products: 'Products',
    reports: 'Reports',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Logout',
    financial_portal: 'FaidaPlus Financial Portal',
    live_account: 'Live Account',
    enterprise_view: 'Enterprise View',
    more: 'More',
    business_control_panel: 'Business Control Panel',
    active_workspace: 'Active Workspace',

    // Dashboard
    growth_hub: 'Your growth hub',
    dashboard_desc: 'A live overview of cashflow, inventory health, and revenue momentum for your business.',
    live_sync: 'Live sync enabled',
    total_income: 'Total Income',
    total_expenses: 'Total Expenses',
    net_profit: 'Net Profit',
    low_stock: 'Low Stock',
    income_vs_expenses: 'Income vs Expenses',
    weekly_trend: 'Weekly trend for the last 7 days',
    auto_updating: 'Auto-updating',
    expense_breakdown: 'Expense Breakdown',
    monthly_spend: 'This month’s spend by category',
    recent_transactions: 'Recent Transactions',
    recent_desc: 'Latest activity from your ledger.',
    view_all_transactions: 'View all transactions',
    no_transactions_yet: 'No transactions yet. Add one to see live updates here.',
    
    // Insights
    revenue_pulse: 'Revenue pulse',
    stock_watch: 'Stock watch',
    growth_insight: 'Growth insight',
    profit_stable: 'Profit is stable and trending upward.',
    costs_outpacing: 'Costs are outpacing income — review expenses.',
    on_track: 'On track',
    needs_attention: 'Needs attention',
    inventory: 'Inventory',
    ai_insight: 'AI Insight',
    marketing_focus: 'Focus marketing on your top revenue categories for the strongest return.',
    low_stock_alert: 'items are low in inventory. Restock soon to avoid gaps.',
    single_stock_alert: 'item is low in inventory. Restock soon to avoid gaps.',

    // General Fields
    date: 'Date',
    description: 'Description',
    category: 'Category',
    amount: 'Amount',
    type: 'Type',
    status: 'Status',
    actions: 'Actions',
    income: 'Income',
    expense: 'Expense',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    search: 'Search',
    loading: 'Loading...',
    all: 'All',

    // Transaction Categories
    'Sales': 'Sales',
    'Service': 'Service',
    'Other Income': 'Other Income',
    'Stock Purchase': 'Stock Purchase',
    'Rent': 'Rent',
    'Utilities': 'Utilities',
    'Transport': 'Transport',
    'Salaries': 'Salaries',
    'Other': 'Other',
    'Food': 'Food',
    'Electronics': 'Electronics',
    'Clothing': 'Clothing',
    'Services': 'Services',
    buying_price_label: 'Buying Price',
    selling_price_label: 'Selling Price',
    stock_label: 'Stock',
    out_of_stock: 'Out of Stock',
    in_stock: 'In Stock',
    record_sale: 'Record Sale',
    quantity_to_sell: 'Quantity to Sell',
    unit_price: 'Unit Price',
    sell: 'Sell',

    // Transactions page
    transactions_hub: 'Transactions ledger',
    transactions_desc: 'Log and monitor every incoming and outgoing transaction to keep your accounts immaculate.',
    add_transaction: 'Add Transaction',
    export_pdf: 'Export PDF',
    filter_by_type: 'Filter by Type',
    filter_by_category: 'Filter by Category',
    filter_by_status: 'Filter by Status',
    search_placeholder: 'Search by description or category...',
    no_transactions_found: 'No transactions found matching your criteria.',
    new_transaction_title: 'New Ledger Entry',
    edit_transaction_title: 'Edit Ledger Entry',
    transaction_amount: 'Amount (TZS)',
    transaction_type: 'Transaction Type',
    transaction_category: 'Category',
    transaction_date: 'Date',
    transaction_status: 'Status',
    transaction_desc_label: 'Description',
    pending: 'Pending',
    completed: 'Completed',
    failed: 'Failed',

    // Products page
    inventory_hub: 'Inventory & Products',
    inventory_desc: 'Manage your stock levels, tracking margins, costs, and selling prices effortlessly.',
    add_product: 'Add Product',
    product_name: 'Product Name',
    sku: 'SKU',
    stock_quantity: 'Stock Quantity',
    cost_price: 'Cost Price',
    selling_price: 'Selling Price',
    profit_margin: 'Profit Margin',
    low_stock_threshold: 'Low Stock Threshold',
    no_products_found: 'No products in inventory yet. Add your first product!',
    new_product_title: 'New Inventory Item',
    edit_product_title: 'Edit Inventory Item',
    product_details: 'Product Details',
    stock_and_alerts: 'Stock & Alerts',
    pricing_and_margins: 'Pricing & Margins',
    units: 'units',

    // Reports page
    financial_reports: 'Financial Reports',
    reports_desc: 'Generate, analyze, and print comprehensive financial statements for your records.',
    statement_type: 'Statement Type',
    income_statement: 'Income Statement',
    tax_summary: 'Tax & Sales Summary',
    expense_report: 'Category Expense Report',
    generate_report: 'Generate Report',
    period_monthly: 'This Month',
    period_quarterly: 'This Quarter',
    period_yearly: 'This Year',
    gross_revenue: 'Gross Revenue',
    total_cost_goods: 'Cost of Goods Sold (COGS)',
    gross_profit: 'Gross Profit',
    operating_expenses: 'Operating Expenses',
    net_earnings: 'Net Earnings (Profit)',
    tax_liability: 'Estimated Tax (VAT 18%)',
    sales_count: 'Total Sales Count',
    download_pdf: 'Download PDF Report',
    report_not_generated: 'Configure options and click generate to view the report.',
    daily_report: 'Daily',
    weekly_report: 'Weekly',
    monthly_report: 'Monthly',
    custom_report: 'Custom',
    generating: 'Generating...',
    total_revenue: 'Total Revenue',
    transaction_summary: 'Transaction Summary',
    income_transactions: 'Income Transactions',
    expense_transactions: 'Expense Transactions',
    total_transactions: 'Total Transactions',
    category_breakdown: 'Category Breakdown',
    no_report_yet: 'No report generated yet',
    select_report_desc: 'Select a report type above to generate your financial insights',

    // Settings page
    settings_hub: 'Account & Portal Settings',
    settings_desc: 'Customize your business profile, notification preferences, security, and interface language.',
    language: 'Language / Lugha',
    english: 'English',
    swahili: 'Swahili (Kiswahili)',
    business_profile: 'Business Profile',
    security_credentials: 'Security & Credentials',
    full_name: 'Full Name',
    email_address: 'Email Address',
    business_name: 'Business Name',
    business_address: 'Business Address',
    phone_number: 'Phone Number',
    currency: 'Default Currency',
    change_password: 'Change Password',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_new_password: 'Confirm New Password',
    update_profile: 'Update Profile',
    update_password: 'Update Password',
    profile_label: 'Profile',
    business_label: 'Business',
    notifications_label: 'Notifications',
    theme_label: 'Theme',
    security_label: 'Security',
    preferences_label: 'Preferences',

    // Notifications page
    notification_center: 'Notification Center',
    notification_desc: 'Stay informed on low stock alerts, transaction events, and business insights.',
    mark_all_read: 'Mark all as read',
    clear_all: 'Clear all notifications',
    no_notifications: 'Your inbox is clear. No new notifications!',

    // Auth (Login / Register)
    sign_in_title: 'Sign in to FaidaPlus',
    sign_in_subtitle: 'Enter your credentials to access your business ledger',
    dont_have_account: "Don't have an account?",
    register_now: 'Register now',
    create_account_title: 'Create your business account',
    create_account_subtitle: 'Join FaidaPlus today to streamline your business tracking',
    already_have_account: 'Already have an account?',
    sign_in_now: 'Sign in here',
    register: 'Register',
    sign_in: 'Sign In',
    password: 'Password',
    confirm_password: 'Confirm Password',
    signing_in: 'Signing in...',
    registering: 'Creating account...'
  },
  sw: {
    // Navigation & Layout
    management: 'Usimamizi',
    dashboard: 'Dashibodi',
    transactions: 'Miamala',
    products: 'Bidhaa',
    reports: 'Ripoti',
    notifications: 'Taarifa',
    settings: 'Mipangilio',
    logout: 'Ondoka',
    financial_portal: 'Tovuti ya Kifedha ya FaidaPlus',
    live_account: 'Akaunti Hai',
    enterprise_view: 'Mtazamo wa Biashara',
    more: 'Zaidi',
    business_control_panel: 'Jopo la Udhibiti wa Biashara',
    active_workspace: 'Eneo la Kazi Hai',

    // Dashboard
    growth_hub: 'Kitovu chako cha ukuaji',
    dashboard_desc: 'Maelezo ya moja kwa moja ya mtiririko wa pesa, afya ya bidhaa ghalani, na kasi ya mapato kwa biashara yako.',
    live_sync: 'Ulandanishaji unafanya kazi',
    total_income: 'Jumla ya Mapato',
    total_expenses: 'Jumla ya Matumizi',
    net_profit: 'Faida Halisi',
    low_stock: 'Bidhaa Chache',
    income_vs_expenses: 'Mapato dhidi ya Matumizi',
    weekly_trend: 'Mwenendo wa wiki kwa siku 7 zilizopita',
    auto_updating: 'Inajisasisha yenyewe',
    expense_breakdown: 'Mchanganuo wa Matumizi',
    monthly_spend: 'Matumizi ya mwezi huu kwa kila kundi',
    recent_transactions: 'Miamala ya Hivi Karibuni',
    recent_desc: 'Shughuli za hivi karibuni kutoka kwenye daftari lako.',
    view_all_transactions: 'Angalia miamala yote',
    no_transactions_yet: 'Hakuna miamala bado. Ongeza mmoja ili uone mabadiliko hapa.',

    // Insights
    revenue_pulse: 'Kasi ya mapato',
    stock_watch: 'Ufuatiliaji wa bidhaa',
    growth_insight: 'Ushauri wa ukuaji',
    profit_stable: 'Faida iko imara na inaongezeka kuelekea juu.',
    costs_outpacing: 'Gharama zinazidi mapato — kagua matumizi yako.',
    on_track: 'Kwenye mstari mzuri',
    needs_attention: 'Inahitaji uangalifu',
    inventory: 'Mali Ghalani',
    ai_insight: 'Ushauri wa AI',
    marketing_focus: 'Elekeza nguvu za masoko kwenye bidhaa zenye mauzo makubwa kwa faida bora.',
    low_stock_alert: 'bidhaa ziko chini ya kiwango ghalani. Jaza stoki haraka.',
    single_stock_alert: 'bidhaa iko chini ya kiwango ghalani. Jaza stoki haraka.',

    // General Fields
    date: 'Tarehe',
    description: 'Maelezo',
    category: 'Kundi / Kategoria',
    amount: 'Kiasi',
    type: 'Aina',
    status: 'Hali',
    actions: 'Vitendo',
    income: 'Mapato',
    expense: 'Matumizi',
    add: 'Ongeza',
    edit: 'Hariri',
    delete: 'Futa',
    cancel: 'Ghairi',
    save: 'Hifadhi',
    search: 'Tafuta',
    loading: 'Inapakia...',
    all: 'Zote',

    // Transaction Categories
    'Sales': 'Mauzo',
    'Service': 'Huduma',
    'Other Income': 'Mapato Mengine',
    'Stock Purchase': 'Ununuzi wa Stoki',
    'Rent': 'Kodi ya Pango',
    'Utilities': 'Bili (Maji/Umeme)',
    'Transport': 'Usafiri',
    'Salaries': 'Mishahara',
    'Other': 'Mengineyo',
    'Food': 'Chakula',
    'Electronics': 'Vifaa vya Umeme',
    'Clothing': 'Mavazi',
    'Services': 'Huduma',
    buying_price_label: 'Bei ya Kununulia',
    selling_price_label: 'Bei ya Kuuzia',
    stock_label: 'Stoki',
    out_of_stock: 'Imeisha Stoki',
    in_stock: 'Ipo Stoki',
    record_sale: 'Sajili Mauzo',
    quantity_to_sell: 'Kiasi cha Kuuza',
    unit_price: 'Bei ya Kikokotoni',
    sell: 'Uza',

    // Transactions page
    transactions_hub: 'Daftari la miamala',
    transactions_desc: 'Sajili na ufuatilie kila muamala unaoingia na kutoka ili kuweka hesabu zako sawa.',
    add_transaction: 'Ongeza Muamala',
    export_pdf: 'Pakua PDF',
    filter_by_type: 'Chuja kwa Aina',
    filter_by_category: 'Chuja kwa Kategoria',
    filter_by_status: 'Chuja kwa Hali',
    search_placeholder: 'Tafuta kwa maelezo au kundi...',
    no_transactions_found: 'Hakuna miamala iliyopatikana kulingana na vigezo vyako.',
    new_transaction_title: 'Ingizo Jipya la Daftari',
    edit_transaction_title: 'Hariri Ingizo la Daftari',
    transaction_amount: 'Kiasi (TZS)',
    transaction_type: 'Aina ya Muamala',
    transaction_category: 'Kundi / Kategoria',
    transaction_date: 'Tarehe',
    transaction_status: 'Hali ya Muamala',
    transaction_desc_label: 'Maelezo',
    pending: 'Inasubiri',
    completed: 'Imekamilika',
    failed: 'Imefeli',

    // Products page
    inventory_hub: 'Stoki & Bidhaa',
    inventory_desc: 'Dhibiti viwango vya stoki, faida, gharama, na bei za mauzo kwa urahisi kabisa.',
    add_product: 'Ongeza Bidhaa',
    product_name: 'Jina la Bidhaa',
    sku: 'Nambari ya Bidhaa (SKU)',
    stock_quantity: 'Kiasi cha Stoki',
    cost_price: 'Bei ya Kununulia',
    selling_price: 'Bei ya Kuuzia',
    profit_margin: 'Asilimia ya Faida',
    low_stock_threshold: 'Kiwango cha Chini cha Stoki',
    no_products_found: 'Hakuna bidhaa ghalani bado. Ongeza bidhaa yako ya kwanza!',
    new_product_title: 'Kitu Kipya cha Stoki',
    edit_product_title: 'Hariri Kitu cha Stoki',
    product_details: 'Maelezo ya Bidhaa',
    stock_and_alerts: 'Stoki & Arifa',
    pricing_and_margins: 'Bei & Faida',
    units: 'vizio',

    // Reports page
    financial_reports: 'Ripoti za Kifedha',
    reports_desc: 'Tengeneza na uchambue ripoti kamili za kifedha kwa ajili ya kumbukumbu zako.',
    statement_type: 'Aina ya Ripoti',
    income_statement: 'Ripoti ya Mapato na Matumizi',
    tax_summary: 'Muhtasari wa Kodi na Mauzo',
    expense_report: 'Ripoti ya Matumizi kwa Kundi',
    generate_report: 'Tengeneza Ripoti',
    period_monthly: 'Mwezi Huu',
    period_quarterly: 'Robo Mwaka Hii',
    period_yearly: 'Mwaka Huu',
    gross_revenue: 'Jumla ya Mapato Mauzo',
    total_cost_goods: 'Gharama ya Bidhaa Zilizouzwa (COGS)',
    gross_profit: 'Jumla ya Faida Kabla ya Gharama',
    operating_expenses: 'Gharama za Uendeshaji',
    net_earnings: 'Mapato Halisi (Faida)',
    tax_liability: 'Kodi Inayokadiriwa (VAT 18%)',
    sales_count: 'Jumla ya Idadi ya Mauzo',
    download_pdf: 'Pakua Ripoti ya PDF',
    report_not_generated: 'Chagua vigezo na bofya tengeneza ili kuona ripoti.',
    daily_report: 'Kila Siku',
    weekly_report: 'Kila Wiki',
    monthly_report: 'Kila Mwezi',
    custom_report: 'Maalum',
    generating: 'Inatengeneza...',
    total_revenue: 'Jumla ya Mapato',
    transaction_summary: 'Muhtasari wa Miamala',
    income_transactions: 'Miamala ya Mapato',
    expense_transactions: 'Miamala ya Matumizi',
    total_transactions: 'Jumla ya Miamala',
    category_breakdown: 'Mchanganuo wa Vikundi',
    no_report_yet: 'Hakuna ripoti iliyotengenezwa bado',
    select_report_desc: 'Chagua aina ya ripoti hapo juu ili kuzalisha uchambuzi wako vya kifedha',

    // Settings page
    settings_hub: 'Mipangilio ya Akaunti & Tovuti',
    settings_desc: 'Binafsisha wasifu wa biashara yako, arifa, usalama, na lugha ya mfumo.',
    language: 'Language / Lugha',
    english: 'Kiingereza (English)',
    swahili: 'Kiswahili (Swahili)',
    business_profile: 'Wasifu wa Biashara',
    security_credentials: 'Usalama & Nywila',
    full_name: 'Jina Kamili',
    email_address: 'Barua Pepe',
    business_name: 'Jina la Biashara',
    business_address: 'Anwani ya Biashara',
    phone_number: 'Nambari ya Simu',
    currency: 'Sarafu Default',
    change_password: 'Badilisha Nywila',
    current_password: 'Nywila ya Sasa',
    new_password: 'Nywila Mpya',
    confirm_new_password: 'Thibitisha Nywila Mpya',
    update_profile: 'Sasisha Wasifu',
    update_password: 'Sasisha Nywila',
    profile_label: 'Wasifu Wako',
    business_label: 'Biashara',
    notifications_label: 'Arifa',
    theme_label: 'Mandhari',
    security_label: 'Usalama',
    preferences_label: 'Mapendeleo',

    // Notifications page
    notification_center: 'Kituo cha Arifa',
    notification_desc: 'Pata taarifa kuhusu upungufu wa bidhaa ghalani, miamala, na ushauri wa biashara.',
    mark_all_read: 'Weka zote kuwa zimesomwa',
    clear_all: 'Futa arifa zote',
    no_notifications: 'Kasha lako la arifa liko wazi. Hakuna arifa mpya!',

    // Auth (Login / Register)
    sign_in_title: 'Ingia kwenye FaidaPlus',
    sign_in_subtitle: 'Weka taarifa zako ili uweze kuona daftari la biashara',
    dont_have_account: 'Je, huna akaunti bado?',
    register_now: 'Sajili sasa hivi',
    create_account_title: 'Sajili akaunti ya biashara yako',
    create_account_subtitle: 'Jiunge na FaidaPlus leo ili kurahisisha ufuatiliaji wa biashara yako',
    already_have_account: 'Tayari una akaunti?',
    sign_in_now: 'Ingia hapa',
    register: 'Sajili Akaunti',
    sign_in: 'Ingia Mfumo',
    password: 'Nywila (Password)',
    confirm_password: 'Thibitisha Nywila',
    signing_in: 'Unapoingia...',
    registering: 'Tunasajili...'
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    const saved = localStorage.getItem('language');
    return saved === 'sw' ? 'sw' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const changeLanguage = (lang) => {
    if (lang === 'en' || lang === 'sw') {
      setLanguage(lang);
    }
  };

  const t = (key) => {
    if (!translations[language]) return key;
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
